### ISSUE TITLE
User Type Detection & Selection

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#23]
When logging into the application, if the user has multiple user types (Admin/Instructor/Student) they should be prompted to select which user type they would like to view the web application as.

**TODO:**
- [x] Create wireframe layout for selecting associated user type/session.
- [x] Connect logic to layout store and routing
- [x] Connect & implement admin user selection
- [x] Connect & implement instructor user selection
- [x] Connect and implement student user selection
- [x] Add button in application bar to allow manual selection. (Change Account View)
