### ISSUE TITLE
Integrate S3 Bucket

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#25]
**TODO**
- [x] Add useS3Bucket hook logic
- [x] Implement private file upload
- [x] Implement public file upload
