### ISSUE TITLE
Instructor Management

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#44]
**TODO**
- [x] Add instructor
- [x] Add row action button and menu
- [x] Archive/Un-Archive
- [x] View groups **Viewing groups is available via the Instructor View Classes link.**

**ON HOLD**
Send an email alert **This feature is currently not needed**
Allow permissions **This feature is currently not needed**

**3.6 Manage Instructors Requirements**
- [x] Admins can give access to the platform to new instructors and manage the program instructors from this screen. Instructors are displayed by Active and Archived.
- [x] The admin can add new instructors to the program, by entering their emails and sending out an invitation for the instructors to create a login and access the internal platform (3.6.1)
- [x] The admin can send an alert message to the instructor.
- [x] The admin can allow or restrict permissions to the sessions. If the permissions are restricted, the admins won’t have access to the sessions.
- [x] The admin can view the groups of the instructor (3.6.3) by selecting each specific session.
- [x] The admin can archive the instructor, this will restrict the access to the platform to the specific instructor. A confirmation modal will be displayed (3.6.2) **I don't think we need a confirmation here.  Instead, we allow the instructor to be un-archived if needed**

![image](https://user-images.githubusercontent.com/24579103/95802753-8e416480-0cbb-11eb-859c-ee3914770b0d.png)
