### ISSUE TITLE
Enforce Instructor Lock, Edit, Remove Permissions

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#45]
For the individual class items, ensure the lock, can lock, edit, remove functionality works as expected.

**TODO**
- [x] For create class, lock the ranking models by default.
- [x] Key Skills use lock/unlock/remove/add workflow.
- [x] Implement isOwner = check parentUserId and userId
- [x] Survey Questions use lock/unlock/remove/add workflow.
- [x] If a survey question is locked, it can only be un-locked by the original owner.
- [x] Class Presentations and Class Resources can only be edited and removed if un-locked.
- [x] If a class resource is locked, it can only be un-locked by the original owner.

**ADDITIONAL TODO**
- [x] Simplify can lock/locked status.  We should only need one locked variable in the database to accomplish everything we 
need.  The can lock status can be enforced via code and the associated item group.
- [x] How will locking/can lock work for instructor created classes?  **Only the creator of a class can lock/unlock an item**
- [x] Enforce Locked permission
- [x] Allow edits when not locked
- [x] Allow remove when not locked
- [x] If any item is removed, a confirmation dialog will appear first

![image](https://user-images.githubusercontent.com/24579103/96478523-009ed100-11f5-11eb-999c-711a395df2e3.png)
![image](https://user-images.githubusercontent.com/24579103/96478583-13b1a100-11f5-11eb-893e-123cd5037695.png)
