### ISSUE TITLE
Class Reports

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#46]
**TODO**
- [x] Create wireframe
- [x] Create age chart component
- [x] Connect age chart component to student data
- [x] Create survey result component
- [x] Connect survey result component -> Student pre-survey data (averages)
- [x] Connect survey result component -> Student post-survey data (averages)
- [x] Create class participant section
- [x] Connect View Report button to show individual student answers

**2.4.6 View Class Report Requirements**
- [x] Instructors can view the average group answers on the Pre and Post Survey.
- [x] The instructor can select a specific student in order to view their answers for the survey questions (2.4.8).

**3.5.6 View Class Report Requirements**
- [x] Admins can view the average group answers on the Pre and Post Survey.
- [x] The admin can select a specific student in order to view their answers for the survey questions (3.5.8)

![image](https://user-images.githubusercontent.com/24579103/95904417-b92bc700-0d54-11eb-921f-7941996c5ece.png)
