### ISSUE TITLE
Attendance History

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#47]
**TODO**
- [x] Add Attendance History Table
    - [x] Create class and group information columns and connect data
- [x] Add Attendance History Table Dialog
- [x] Add Edit Attendance Dialog
- [x] Connect to backend

**Requirements View Attendance History (2.4.5)**
- [x] The user can select a specific date and view that group’s attendance.
- [x] the user can edit the attendance if necessary.
