### ISSUE TITLE
Pre-Release Checklist

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#58]
**TODO**
- [x] Review code for any unused files and cleanup as needed.
- [x] Fix class status that shows completed for new student? **Could not reproduce, must have been fixed by another fix**
- [x] Clean database and run through each workflow and create multiple users of each type.
- [x] Verify accurate completed, pending states between different users.
- [x] Review instructor invite workflow and ensure it is easy and makes sense.  Update if necessary.
- [x] Review student invite workflow and group creation.  Ensure the process makes sense and update if necessary.
- [x] Verify reporting data is accurate.

**Documentation**
- [x] Document process for creating a new admin user
- [x] Document process for creating a new instructor
- [x] Document process for creating a new student (invite, create account, how invites work)
- [x] Document process for creating a new class (admin, instructor relationship)
- [x] Document process for creating a new instructor group
