### ISSUE TITLE
Initial Release Bug Tracking

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#59]
- [x] Add Create New Account button to the accept invite page
- [x] Possible bug reported regarding new student creation and user id not existing.  Awaiting additional information.
- [x] I can't scroll down to save the changes to my profile. I have attached a video to display this in an email.
- [x] The ericajc@bu.edu email was added as a student to the emrvilla@gmail.com instructor. However it's still not working so I have attached screenshots of what I saw when I clicked the accept invite. Afterwards I created an account but when I logged in with the same password it didn't work.  **See comments below.  Marking as complete, let me know if you still have issues**
<img width="692" alt="Screen Shot 2020-10-28 at 3 41 25 PM" src="https://user-images.githubusercontent.com/70787908/97489110-8299a300-1935-11eb-8234-86af7e5d2012.png">
<img width="418" alt="Screen Shot 2020-10-28 at 3 41 21 PM" src="https://user-images.githubusercontent.com/70787908/97489125-875e5700-1935-11eb-858a-1654d6b57848.png">
<img width="747" alt="Screen Shot 2020-10-28 at 3 55 19 PM" src="https://user-images.githubusercontent.com/70787908/97489545-0e133400-1936-11eb-81e1-b8612a2107ad.png">
also if someone needs to create an account to accept the invite can there be a button for that here since currently they would have to press logout to get to main screen then click create an account? **Yes, I will add it to the list**
<img width="558" alt="Screen Shot 2020-10-28 at 3 55 36 PM" src="https://user-images.githubusercontent.com/70787908/97489552-110e2480-1936-11eb-9888-8021eeae9e60.png">
