### ISSUE TITLE
Initial Release Changes & Modifications

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#60]
**TODO**

- [x] When an admin adds a new student into a group, each email added seems to be saved as 'ecamach1' instead of their email. Once they accept the invite, create the account, and save their profile information, ecamach1 changes to their email. Could you make it so their email is saved first instead of the ecamach1? **This looks like a bug that I will fix.  To reproduce, add a new student to a group as an admin.**
- [x] I saved my profile page for the email iamerica13@yahoo.com under instructor ericamacho13@gmail.com but every time I log out and log back in again I am prompted to fill it out again. Can we make it so that the next time you login the profile information is saved already and the first page you see is "my classes"
and workflow. If time permits, this will be implemented after the calendar is completed**
- [x]  A small edit  to the DOORS website. In the Terms and Conditions, can you change "research party" to "research study"?
- [x] When a student clicks "help" their message should go to the instructor and not the admin, but when instructors send a message through help it should go to the admin.
  - [x] Auto sync user's email to ensure we have latest instructor email address.
- [x] When students click "help" can you add the following statement for liability purposes: This interface is not monitored . If you are having thoughts of suicide or self-harm, please call 1-800-273-8255.
- [x] Add ability for  new user to request an invite if they do not have any yet.
- [x] Password - Make the input a live error status and show all of the errors at once (capitalization, number, etc)
- [x] Add duplicate save button to bottom of edit class materials.
- [x] When creating an account, disable the enter button on the login form while the new account dialog is open.
- [x] Add Instructor Groups tab and ability to click view instructors in the admin instructor table.
- [x] Update terms and conditions to use correct verbiage (not medical advice).
- [x] Require the user to complete their profile before using the application. 
    - [x] Create a username (please do not use any personally identifiable information when creating your username. This includes your first or last name or your birthdate): Text box​ (required)
    - [x] If you would like to receive reminders on your phone or computer, please enter your phone number or email address: Text box​ (optional). **EDIT: Change to: If you would like to receive reminders on your phone, please enter your phone number: Text box (optional)**
    - [x] Also, I'm just now thinking that people from our programs won't have much digital literacy so it might be helpful to put (required) and (optional) instead of * or maybe a key that says * = required.
    - [x] Do you work at or receive services from Vinfen? Yes or No
    - [x] Are you a clinician, a person served by Vinfen or other? 
    - [x] If they choose served by Vinfen, then the following question appears:  **What program are you affiliated with? Click all that apply between: “I go to a Clubhouse”; “I go to a Recovery Learning Center”, “I go to an outpatient clinic”; “I live in a Vinfen group home”; “I receive services from a Vinfen team (outreach worker, peer support, housing support, etc)” “Other”**
    - [x] ​If they choose clinician, then the following question appears:  **What Hospital, Clinic, or community based mental health program are you affiliated with? Text box**
- [x] During the invite process, prompt the user with a dialog that says "I agree to be part of research party...".  
- [x] Add admin ability to unlock any locked items regardless of owner status
- [x] Lesson Plans - Embed videos into page and validate that the user has clicked on the videos before they can proceed.
- [x] In the Class Roster and Groups pages, add the ability to move a student from one group to another.
    - [x] Remove the Session->Group linkage is it will no longer be used since students can be moved.
- [x] Make initial profile page scrollable content
- [x] Instead of welcome, 'email' can it read welcome, 'username' if they saved it?
- [x] When people click other for the 'Are you a clinician, a person served by Vinfen or other?' it needs a text box
- [x] Modify sender to read 'DOORS' instead of 'doors' when people get invites for the account
