### ISSUE TITLE
Research Party Agreement

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#64]
**TODO**
- [x] Add agreement text
- [x] Add terms and conditions link

![image](https://user-images.githubusercontent.com/24579103/97319094-28fc8000-1832-11eb-8f0f-aec3709f6d20.png)

**Original Email**
For this content that was needed: 

- [x] During the invite process, prompt the user with a dialog that says "I agree to be part of research party...".  

It should read: 

By creating an account, I agree that my progress in digital learning can be used for assessing the overall effectiveness of lessons. All data collected will not contain personal healthcare information and will be anonymized and de-identified for analysis and does. I also agree to the Terms and Conditions which may be accessed below. 

*blue writing for the Terms and Conditions for them to click on it*

*I agree and I do not agree buttons* under that

If they do not agree we would like to include a pop up of sorts or a statement that reads "Unfortunately, you cannot participate at this time without agreeing to terms. Please contact team@digitalpsych.org to learn more."
