### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by cvanem** [BIDMCDigitalPsychiatry/DOORS#69]
**Original Calendar Requirements**
----

[Original Admin Calendar Requirements](https://github.com/cvanem/doors/issues/49)
[Original Instructor Calendar Requirements](https://github.com/cvanem/doors/issues/48)
[Original Student Calendar Requirements](https://github.com/cvanem/doors/issues/6)

**New Calendar Requirements**
----
- [x] Admins can view all events via the calendar tab.
- [x] Admins can edit/delete existing events
- [x] Instructors can create/edit/delete their own events
- [x] Instructors can mark attendance for their associated events/students.  This will work similar to class attendance, but will be performed from the Calendar page.
- [x] Instructors can view attendance history for associated events/students.
- [x] Students can view their associated instructor events

**TODO**
- [x] Implement permissions for create/edit/view
- [x] Connect permissions to different user types
- [x] Filter event data based on user type and instructor linkages.
    - [x] Admin's should see all events
    - [x] Instructors should see only their events
    - [x] Students should see only their instructor's events
- [x] Implement event attendance

**Outstanding Questions**
----
**Admin Questions**
- [x] Do admin's need the ability to view events?  If yes, should the admin see all events or only the events for instructors whom they invited?  **Admin should see all events.
- [x] Do admin's need the ability to create events?  If yes, we will need to add support for specifying an associated instructor  when creating the event.  We can do this by adding a View Classes link in the instructor table, or adding a drop down to the new event dialog where the admin selects the associated instructor. **No**
- [x] Do admin's need the ability to edit events? **Yes**

**Instructor Questions**
- [x]  Should an instructor be limited to only viewing their associated events or should they see all events from all instructors?

**Student Questions**
- [x]  Should a student be limited to only viewing events from their associated instructor or should they see all events?
